### ISSUE TITLE
Change compile scripts to link against portaudio

### ISSUE THREAD

**Issue by bastibe** [TGM-Oldenburg/Msound#1]
Currently, portaudio is compiled right into msound. Compilation would be much easier if msound merely linked against portaudio.

**Comment by Janwillhaus** [comment]
I just realized this was still an open ticket … I am going to merge this into master soon. It's the perfect solution and the requirement for brew is absolutely acceptable. Anyone with aspirations to compile anything on the Mac should have it installed anyway, IMHO.

**Comment by Janwillhaus** [comment]
The only thing coming up is the removed "legacy support" flag (as mentioned in #11). So if we agree on dropping <R2006b support, 7cacfe64c8db30c77dd3817635e5ecaa4c51ee2d can be merged right away.

**Comment by bastibe** [comment]
I'm all for that. An interesting twist on this might be to include [pre-compiled versions of portaudio.dll](https://github.com/bastibe/PySoundCard/tree/master/_soundcard_data).

**Comment by Janwillhaus** [comment]
So only for Windows I presume? Both Mac and Linux have proper package managers (and almost OOTB-working build environments) to get the latest and greasted version of PortAudio. I have to admit I'm not a big fan of binaries in the repository.

**Comment by Janwillhaus** [comment]
I am not a big fan of including any binaries ... but it would drastically simplify compiling for Windows.
