### ISSUE TITLE
"How to build msound" PDF contains outdated links, should be converted to Markdown

### ISSUE THREAD

**Issue by Janwillhaus** [TGM-Oldenburg/Msound#10]
Steinberg seems to recently have changed their link structure, and the URL to the 3rd party SDK mentioned in `How to build msound.pdf` is not valid anymore. Furthermore to increase maintainability for such how-to guides, they should be written in Markdown and not a compiled PDF. I also advocate renaming the file, going by a [fairly widely used convention](https://github.com/search?utf8=%E2%9C%93&q=filename%3ABUILD.md&type=Code&ref=searchresults): `BUILD.md`, what do you think @bastibe?

**Comment by Janwillhaus** [comment]
I started working on this but the contents of the new how-to are dependant on #11, #1, and #8. Those should be resolved first.

**Comment by bastibe** [comment]
I agree
