### ISSUE TITLE
Has anyone ever tested Msound with Matlab older than R2006b?

### ISSUE THREAD

**Issue by Janwillhaus** [TGM-Oldenburg/Msound#11]
We theoretically provide support for versions of Matlab older than R2006b in the compile scripts but I don't see anyone testing if Msound actually still works well with those. Generally speaking I don't see the point in maintaining (untested!) support for Matlab releases that are about to turn ten years old in a few months. 

Thus I am advocating to drop the "legacy mode" flag from all compile scripts, cleaning them up along the way.

**Comment by bastibe** [comment]
I am all for supporting only one student-batch worth of versions, i.e. support at most Matlab versions from four years ago.
