### ISSUE TITLE
Can we drop the Visual Studio related files?

### ISSUE THREAD

**Issue by Janwillhaus** [TGM-Oldenburg/Msound#12]
In my crusade to higher levels of simplicity, I'd like to get rid of the Visual Studio related files, namely

```
msound.def
msound_dll.def
msound_msvc2003*
```
I don't see the point of keeping them around, as the easiest way to compile Msound on Windows is using MATLAB and the `compile_msound_win.` script.

**Comment by bastibe** [comment]
definitely a good idea! The less clutter, the better.
