### ISSUE TITLE
Provide up-to-date binaries for Windows, Linux and Mac.

### ISSUE THREAD

**Issue by bastibe** [TGM-Oldenburg/Msound#2]
The current binaries are quite outdated, and there are no binaries for the Mac. 

Now that we have Mac compatibility, we should provide up-to-date binaries.

Also, the current binaries link against a very old version of portaudio. Sadly, the current version of portaudio can not be compiled with the LCC-compiler on Windows. Thus, this depends on #1, which would remove the necessity for compiling portaudio.

**Comment by Janwillhaus** [comment]
This issue got a little bit left behind. We now *do* provide up-to-date binaries, all linking against the current stable portaudio (January 30, 2014, SVN rev 1919).

This leaves the case of portaudio sources being required for a Windows compile ... that needs to be discussed.
