### ISSUE TITLE
Some Linux Distros dont provide all PA Hosts

### ISSUE THREAD

**Issue by Janwillhaus** [TGM-Oldenburg/Msound#8]
@SvenFranz just encountered an error compiling Msound from sources on Ubuntu using my tips from PR #6. Unfortunately Ubuntu obviously ships a pre-compiled version of the portaudio library, which has only OSS and ALSA compiled in. This leads to the build flags in  `compile_msound_linux.m` to be completely ignored.

I figured out the only way to circumvent this is to compile PA from sources as-well, adding the staticly compiled PA lib to the Msound directory and modifying the build-script to utilize that version of PA.

#### 1. Compile PA

```bash
# Download the latest version of portaudio
wget http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz
tar xzfv pa_stable_v19_20140130.tgz

# Configure and compile it with the wanted host API(s) (always use --with-pic, too!)
cd portaudio
./configure --with-jack --with-pic && make

# copy the lib and header file over to the Msound repository directory
cp lib/.libs/libportaudio.a include/portaudio.h /path/to/Msound/
```

#### 2. Modify Msound compiling script

Change [line 99](https://github.com/TGM-Oldenburg/Msound/blob/master/compile_msound_linux.m#L99) of `compile_msound_linux.m` to the following:

```matlab
eval( [ 'mex', szOptions, szDefines, szPaths, szFiles, szLibs ' libportaudio.a'] );
```

Make sure to set the flags `bOss`, `bAlsa`, and `bJack` correctly as well! Now run the comile script

### Long-term Solution

The next step should be to incorporate this process into the compile script to make it a one-click solution again (which is its purpose IMHO).

**Comment by Janwillhaus** [comment]
After some digging it turns out to be a non-trivial fix. Only possible way would be to go back to compiling from sources as we did before for non-standard host API requirements.

**Comment by bastibe** [comment]
Still, linking to the system portaudio is the right way to do it. If someone needs a special portaudio, he should compile it himself.

**Comment by Janwillhaus** [comment]
Now that I think about it, that's propably the most sensible way to see it. In that case, I'd suggest

* checking if the linux compile flags do work on *any* popular distro (debianoid, RH, Arch—which I don't expect them to) and discard them otherwise. 
* adding a section to the README on how to custom-compile PA to properly work with Msound.
